# @package hydra.job_logging
version: 1
formatters:
  detailed:
    format: "[%(asctime)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: detailed
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    formatter: detailed
    filename: run.log

root:
  handlers: [console, file]
  level: INFO

disable_existing_loggers: false
