# Word Association: Generate Embedding

defaults:
  - /base
  - _self_

experiment_name: word_association
task: generate_embedding

# === Parameters ===
seed: 42
rank: 50
max_outer: 1000
use_all_responses: false
top_n_words: null
min_word_length: 1
symmetrization: geometric_mean
bidirectional_only: false

# === Compute ===
n_jobs: 16

# === Paths ===
data_dir: ${paths.data_dir}/small-world-of-words
ratings_data_dir: ${paths.data_dir}
