# Word Association: Predict Behavioral Properties

defaults:
  - /base
  - _self_

experiment_name: word_association
task: predict_behavioral_properties

# === Parameters ===
seed: 42
rank: 50
embedding_dir: generate_embedding/50
pole_size: 20
n_outer_folds: 5
n_inner_folds: 3

# === Compute ===
n_jobs: 16

# === Paths ===
data_dir: ${paths.data_dir}/small-world-of-words
ratings_data_dir: ${paths.data_dir}
