# @package _global_
hydra:
  job:
    chdir: true
  run:
    dir: ${project_root}/outputs/experiments/${experiment_name}/${task}
  sweep:
    dir: ${project_root}/outputs/experiments/${experiment_name}/${task}
    subdir: ${hydra.job.override_dirname}
