# @package _global_
hydra:
  job:
    chdir: true
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: tmp/${hydra.job.num}
