# @package dataset
type: feature_file
path: ${paths.datasets}/deepsim/raw/features/dataset/openai/ViT-L-14/visual
features_file: features.npy
filter_file: ${paths.data_dir}/deepsim/raw/features/image_info.csv
filter_column: filename
filter_pattern: "_plus"
similarity_fn: gaussian_kernel
rank_range: [5, 100, 5]

