# @package dataset
# Mur92 fMRI dataset (92 objects, IT cortex, 15 subjects)

name: mur92
type: neural_rsm
path: ${paths.ssd}/datasets/similarity_datasets/mur92

bounds_task: mur92
rank_range: [1, 20, 1]
