# @package dataset
# Peterson fMRI dataset - Animals subset

name: peterson_animals
loader_name: peterson-animals
type: neural_rsm
path: ${paths.ssd}/datasets/similarity_datasets/peterson

bounds_task: peterson-animals
rank_range: [1, 20, 1]
