# @package dataset
# Peterson fMRI dataset - Various objects subset

name: peterson_various
loader_name: peterson-various
type: neural_rsm
path: ${paths.ssd}/datasets/similarity_datasets/peterson

bounds_task: peterson-various
rank_range: [1, 20, 1]
