# @package dataset
# THINGS Monkey F IT Neural Data (22k images)

name: things-monkey-22k
type: neural_features
path: ${paths.ssd}/fmahner/macaque_florian/22k

# Similarity computation
similarity_fn: gaussian_kernel

# Loading parameters
loader_kwargs:
  monkey_type: "F"
  roi: "it"
  min_reliab: 0.3

# Cross-experiment references
bounds_task: things-monkey-22k-f
rank_range: [5, 50, 5]
