# @package dataset
type: neural_features
path: ${paths.datasets}/nsd
similarity_fn: gaussian_kernel
rank_range: [5, 100, 5]
loader_kwargs:
  roi_name: streams
  space: func1pt8mm
requires: [subject_id]

