[tool.poetry]
name = "tools"
version = "0.0.1"
description = "A collection of tools for machine learning and scientific computing"
authors = ["florianmahner <florian.mahner@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
